### ISSUE TITLE
config.json causes issues

### ISSUE THREAD

**Issue by thomasdelaet** [MicroMinion/1tp#13]
loading config.json causes issues with browserify since file can not be found ... is there another way to do this? (or maybe just disable this mechanism and rely only on env variables)?

**Comment by nicojanssens** [comment]
You can activate TURN by setting the env variables TURN_ADDR, TURN_PORT, TURN_USER, TURN_PASS and ONETP_REGISTRAR. In that case you don't need this config.json file.

**Comment by thomasdelaet** [comment]
I know that. The problem is that browserify crashes on the require statement for config.json

**Comment by nicojanssens** [comment]
Should be fixed.

**Comment by thomasdelaet** [comment]
tnx
