### ISSUE TITLE
implement server.close behavior

### ISSUE THREAD

**Issue by nicojanssens** [MicroMinion/1tp#2]

**Comment by thomasdelaet** [comment]
does this include destroy() function?

When I get an error event, I call destroy(). However I'm currently experiencing a crash because the current implementation of destroy() generates a not-implemented error event => recursion => call stack size exceeded

**Comment by nicojanssens** [comment]
available in 0.14.0 -- but need to extend test suite first before closing this issue

**Comment by nicojanssens** [comment]
tested and debugged -- ready to use as from version 0.16.0
