### ISSUE TITLE
get ip addresses and port in chrome does not work

### ISSUE THREAD

**Issue by thomasdelaet** [MicroMinion/1tp#22]
Loading 1tp in a chrome app results in ip addresses and port being undefined.

Suggestion is to abstract away port finding for tcp and udp and use [node-portfinder](https://github.com/indexzero/node-portfinder) for this so that [chrome-portfinder](https://github.com/feross/chrome-portfinder) can be used as drop-in replacement

I would suggest to split finding local ipv4 addresses in similar modules where you can use os.NetworkInterfaces() on node and chrome.system.network.getNetworkInterfaces on chrome

**Comment by nicojanssens** [comment]
Good catch! 

My tests load a 1tp client in a chrome app, while the server runs in a node process. So I didn't notice this issue yet :-s

Will fix this when I'm back from vacation.

**Comment by nicojanssens** [comment]
Root cause of this problem:

UDP and TCP connections make use of lib/nat/ip-addresses to retrieve all IP addresses of a 1tp endpoint (if needed). The latter relies on os.networkInterfaces, which returns an empty object after browserify replaces the os lib with os-browserify (see https://github.com/CoderPuppy/os-browserify/blob/master/browser.js line 35).

So I'll code a chrome shim to replace os-browserify with an updated version invoking the chrome.system.network.getNetworkInterfaces -- as you also suggested.

Ports are defined, however, when I hard-code local IP addresses. So for now there doesn't seem to be a need to integrate those portfinder modules.

**Comment by thomasdelaet** [comment]
The problem is that retrieving network interfaces info on chrome is async operation while yours is synchronous. 

I would also focus on fixing this problem on cordova, not on chrome given that chrome apps are very soon not going to be relevant anymore.

Note that I did not try to run this on cordova, so no clue on how this will react.
 
Not sure I understand port point: my understanding is that you have two options: either you hard-code or you dont specify a port so the listen() call picks one. Not sure if the latter works on chrome but was not able to test ...

**Comment by nicojanssens** [comment]
Thx. I created a separate branch to resolve this issue properly -- i.e. with support for cordova.

**Comment by thomasdelaet** [comment]
Cool! Looking forward to the clean solution :-)

**Comment by nicojanssens** [comment]
@thomasdelaet should be fixed. Can you verify if my latest updates resolve this problem?

**Comment by thomasdelaet** [comment]
It loads chrome-specific code, so that's great!

Error that I get now is a bit weird since syntax seems to be the right one for ip.isV4Format
Error in response to system.network.getNetworkInterfaces: TypeError: ip.isV4Format is not a function
    at chrome-extension://jdnmglbnlklenlpdbnbnglbfaiemdfgk/index.js:164103:15
    at null.callback (chrome-extension://jdnmglbnlklenlpdbnbnglbfaiemdfgk/index.js:164101:12)
    at getIpAddresses (chrome-extension://jdnmglbnlklenlpdbnbnglbfaiemdfgk/index.js:164100:25)
    at Object.getIpAddressesP (chrome-extension://jdnmglbnlklenlpdbnbnglbfaiemdfgk/index.js:164116:3)
    at Server.<anonymous> (chrome-extension://jdnmglbnlklenlpdbnbnglbfaiemdfgk/index.js:164736:22)
    at Server.EventEmitter.emit (chrome-extension://jdnmglbnlklenlpdbnbnglbfaiemdfgk/index.js:156939:17)
    at chrome.sockets.tcpServer.getInfo [as callback] (chrome-extension://jdnmglbnlklenlpdbnbnglbfaiemdfgk/index.js:252666:12)

**Comment by nicojanssens** [comment]
Did you run an npm update? I recently started using the ip package, so maybe it's not available in your node_modules dir.

**Comment by thomasdelaet** [comment]
thanks!
