### ISSUE TITLE
Consider moving to version 1.0.0

### ISSUE THREAD

**Issue by DiegoRBaquero** [MicroMinion/1tp#32]
Semver for version under 1.0.0 is handled as 0.major.minor

Is better to start in version 1.0.0 to get the full benefits of semver.

**Comment by nicojanssens** [comment]
Hi @DiegoRBaquero,

Agree, but before moving to 1.x.x I'd like to integrate my udp-hole-punching lib (issue #12) + need to fix an annoying TURN bug ...

Once this is done, I will upgrade to version 1.0.0

**Comment by DiegoRBaquero** [comment]
Ah alright. Feel free to close this :)
