### ISSUE TITLE
set port

### ISSUE THREAD

**Issue by thomasdelaet** [MicroMinion/1tp#8]
how can I make UDP and TCP port 'fixed'?

This will be needed when running from containers or on host where we want to hard code connectionInfo (e.g., for DHT seed nodes)

**Comment by thomasdelaet** [comment]
never mind. I'll also need ipv4 address fixed. So I'll just pass connectionInfo with constructor

**Comment by nicojanssens** [comment]
OK. Let me know if the connectionInfo would not be processed properly.
